#!/bin/bash

function region_select(){
    region=$1
    case $region in
    '1')
        reg="SOUTHEAST" ;;
    '2')
        reg="NORTHEAST" ;;
    '3')
        reg="CENTGRLAKES" ;;
    '4')
        reg="NORTHROCKIES" ;;
    '5')
        reg="SOUTHROCKIES" ;;
    '6')
        reg="PACNORTHWEST" ;; 
    '7')
        reg="PACSOUTHWEST" ;;
    '8')
        reg="SOUTHPLAINS" ;;
    '9')
        reg="UPPERMISSVLY" ;;
    '10')
        reg="SOUTHMISSVLY" ;;
    '11')
        reg="ALASKA" ;;
    '12')
        reg="HAWAII" ;;
    '13')
        reg="CARIB" ;;
    '14')
        reg="CONUS-LARGE" ;;
    '15')
        reg="GUAM" ;;
    *)
        echo Improper region selected
        exit
    esac
    map="https://radar.weather.gov/ridge/lite/${reg}_loop.gif"
    echo $map
}

region_support(){
    echo '[1] South East'
    echo '[2] North East'
    echo '[3] Mid West'
    echo '[4] North Rockies'
    echo '[5] South Rockies'
    echo '[6] North West'
    echo '[7] South West'
    echo '[8] South Plains'
    echo '[9] Upper Mississippi Valley'
    echo '[10] South Mississippi Valley'
    echo '[11] Alaska'
    echo '[12] Hawaii'
    echo '[13] Caribean'
    echo '[14] Conus'
    echo '[15] Guam'
}

echo 'Which region do you wish to see the radar of?'
region_support
read -p "Region Name: " region

map=$(region_select $region)
mpv --loop=inf ${map}
