#!/bin/bash

function region_select(){
    region=$1
    case $region in
    'guam')
        reg="GUAM" ;;
    'conus')
        reg="CONUS-LARGE" ;;
    'caribbean')
        reg="CARIB" ;;
    'alaska')
        reg="ALASKA" ;;
    'hawaii')
        reg="HAWAII" ;;
    'uppermissvalley')
        reg="UPPERMISSVLY" ;;
    'southmissvalley')
        reg="SOUTHMISSVLY" ;;
    'southplains')
        reg="SOUTHPLAINS" ;;
    'northwest')
        reg="PACNORTHWEST" ;;
    'southwest')
        reg="PACSOUTHWEST" ;;
    'northrockies')
        reg="NORTHROCKIES" ;;
    'southrockies')
        reg="SOUTHROCKIES" ;;
    'northeast')
        reg="NORTHEAST" ;;
    'southeast')
        reg="SOUTHEAST" ;;
    'midwest')
        reg="CENTGRLAKES" ;;
    *)
        echo Improper region selected
        exit
    esac
    map="https://radar.weather.gov/ridge/lite/${reg}_loop.gif"
    echo $map
}

region_support(){
    echo '[1] South East'
    echo '[2] North East'
    echo '[3] Mid West'
    echo '[4] North Rockies'
    echo '[5] South Rockies'
    echo '[6] North West'
    echo '[7] South West'
    echo '[8] South Plains'
    echo '[9] Upper Mississippi Valley'
    echo '[10] South Mississippi Valley'
    echo '[11] Alaska'
    echo '[12] Hawaii'
    echo '[13] Caribean'
    echo '[14] Conus'
    echo '[15] Guam'
}

echo 'Which region do you wish to see the radar of?'
region_support
read -p "Region Name: " region

case $region in 
    '1')
        val="southeast" ;;
    '2')
        val="northeast" ;;
    '3')
        val="midwest" ;;
    '4')
        val="northrockies" ;;
    '5')
        val='southrockies' ;;
    '6')
        val="northwest" ;;
    '7')
        val="southwest" ;;
    '8')
        val="southplains" ;;
    '9')
        val="uppermissvalley" ;;
    '10')
        val="southmissvalley" ;;
    '11')
        val="alaska" ;;
    '12')
        val="hawaii" ;;
    '13')
        val="caribbean" ;;
    '14')
        val="conus" ;;
    '15')
        val="guam" ;;
    *)
        echo No Region Selected
        exit
esac

map=$(region_select $val)

mpv --loop=inf ${map}
